// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-CG69z63VWolK_pkLmoECof6JYqiUeek',
    appId: '1:739461998978:web:4a35a1011bc535c0eb079b',
    messagingSenderId: '739461998978',
    projectId: 'flutter-temeldenzirveye',
    authDomain: 'flutter-temeldenzirveye.firebaseapp.com',
    storageBucket: 'flutter-temeldenzirveye.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6hSEowKV2NmGu0ih-RVlMBuPet_ZF3Y',
    appId: '1:739461998978:android:2c03e6f2743ca954eb079b',
    messagingSenderId: '739461998978',
    projectId: 'flutter-temeldenzirveye',
    storageBucket: 'flutter-temeldenzirveye.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOZfxtf0VPjUZHsjJGXtK82dFnKI2veTk',
    appId: '1:739461998978:ios:65a2fef875e496bfeb079b',
    messagingSenderId: '739461998978',
    projectId: 'flutter-temeldenzirveye',
    storageBucket: 'flutter-temeldenzirveye.appspot.com',
    iosClientId: '739461998978-6rkkoalvuuqqfgec60a9lrukjv7ohie1.apps.googleusercontent.com',
    iosBundleId: 'com.example.temeldenzirveyeflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOZfxtf0VPjUZHsjJGXtK82dFnKI2veTk',
    appId: '1:739461998978:ios:65a2fef875e496bfeb079b',
    messagingSenderId: '739461998978',
    projectId: 'flutter-temeldenzirveye',
    storageBucket: 'flutter-temeldenzirveye.appspot.com',
    iosClientId: '739461998978-6rkkoalvuuqqfgec60a9lrukjv7ohie1.apps.googleusercontent.com',
    iosBundleId: 'com.example.temeldenzirveyeflutter',
  );
}
